name: Build
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ubuntu Prerequisites
        run: |
          sudo apt-get update || true
          sudo apt-get install build-essential libnuma-dev
      - name: Build
        run: cd userland; make
